-- lab 2 
-- 1. Display actor names in the format: LAST_NAME, First_name (e.g., GUINESS, Penelope).

select concat(upper(last_name) , ', ' , initcap(first_name)) as actor_full_name
from actor;

-- 2. Display all customer emails in lowercase and replace the domain 
-- @sakilacustomer.org with @iti-students.edu

select replace(email, '@sakilacustomer.org', '@iti-students.edu')
from customer;


-- 3. Display the first 50 characters of each film's description followed by "..."
--    and call the column short_summary.

select concat(left(description, 50) , '...') as short_summary
from film;

-- 4. Find all customers who registered in the month of February (any year).


select *
from customer 
where extract(month from create_date) = 2;


-- 5. Use CASE to label rentals as 'Cheap' (under $2), 'Mid' ($2-$4.99), or
--   'Expensive' (above $5). (payment table)

select amount,
    case 
        when amount < 2 then 'cheap'
        when amount between 2 and 4.99 then 'mid'
        else 'expensive'
    end as rental_label
from payment;



-- 1. Create a function that takes actor_id and returns the concatenated first and
--    last name of this actor.

create or replace function get_actor_name(p_actor_id int) 
returns text as $$
declare
    v_full_name text;
begin
    select concat(first_name , ' ' , last_name) 
    into v_full_name 
    from actor 
    where actor_id = p_actor_id;

    return v_full_name;
end;
$$ language plpgsql;

-- test the fuction 
select get_actor_name(1);



-- 2. Create a function that takes customer_id and returns the total count of rentals
--     made by this customer.

create or replace function get_customer_rental_count(p_customer_id int) 
returns int 
as $$
declare
    v_rental_count int;
begin
    select count(*) 
    into v_rental_count 
    from rental 
    where customer_id = p_customer_id;

    return v_rental_count;
end;
$$ language plpgsql;

-- test the function
select get_customer_rental_count(5);




-- 3. Create a function that takes customer_id and returns a result set containing
--    the full name, email, full address, and city of that customer.



create or replace function get_customer_full_info(p_customer_id int) 
returns table (
    full_name text,
    email varchar,
    full_address varchar,
    city varchar
) as $$
begin
    return query
    select 
        concat(c.first_name , ' ' , c.last_name)::text,
        c.email ::varchar,
        a.address::varchar,
        ct.city::varchar
    from customer c
    join address a on c.address_id = a.address_id
    join city ct on a.city_id = ct.city_id
    where c.customer_id = p_customer_id;
end;
$$ language plpgsql;

select * from get_customer_full_info(1);


-- 4. Create a function that takes customer_id and returns the name of the
--  category (e.g., 'Action') that the customer rents most often.

create or replace function get_most_rented_category(p_customer_id int)
returns varchar as $$
declare
    v_category_name varchar;
begin
    select c.name
    into v_category_name
    from category c
    join film_category fc on c.category_id = fc.category_id
    join inventory i on fc.film_id = i.film_id
    join rental r on i.inventory_id = r.inventory_id
    where r.customer_id = p_customer_id
    group by c.name
    order by count(*) desc
    limit 1;

    return v_category_name;
end;
$$ language plpgsql;

select get_most_rented_category(5);

-- 5. Create a function that takes a start_date and end_date and returns the total
--  revenue generated by each store during that period.


create or replace function get_store_revenue(p_start_date date, p_end_date date)
returns table (
    store_id int,
    total_revenue numeric
) as $$
begin
    return query
    select  s.store_id, sum(p.amount)::numeric
    from payment p
    join staff st on p.staff_id = st.staff_id
    join store s on st.store_id = s.store_id
    where p.payment_date::date between p_start_date and p_end_date
    group by s.store_id;
end;
$$ language plpgsql;


select * from get_store_revenue('2001-11-18', '2026-01-22');